/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import javax.swing.JFrame;

/**
 *
 * @author Dragneel
 */
public class CommonInterface extends javax.swing.JFrame {

    /**
     * Creates new form CommonInterface
     */
    public CommonInterface() {
        initComponents();
        
        initializeSelf();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        panelLayers = new javax.swing.JLayeredPane();
        managerPanel = new javax.swing.JPanel();
        managerTab = new javax.swing.JTabbedPane();
        acmanagePanel = new javax.swing.JPanel();
        rescomPanel = new javax.swing.JPanel();
        spoLayeredPanel = new javax.swing.JLayeredPane();
        spoPanel = new javax.swing.JPanel();
        sopLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        spoLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        spoLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        spoLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        spoLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        spoLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        spoLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        spoacBut = new javax.swing.JButton();
        spotablePanel = new javax.swing.JPanel();
        spotableScrollPanel = new javax.swing.JScrollPane();
        spoTable = new javax.swing.JTable();
        spotableBut = new javax.swing.JButton();
        residentPanel = new javax.swing.JPanel();
        residentTab = new javax.swing.JTabbedPane();
        addfundPanel = new javax.swing.JPanel();
        addfundLabel1 = new javax.swing.JLabel();
        paymenttypecomboBox = new javax.swing.JComboBox<>();
        addfundLabel2 = new javax.swing.JLabel();
        amountpaidField = new javax.swing.JTextField();
        tidField = new javax.swing.JTextField();
        addfundLabel3 = new javax.swing.JLabel();
        addfundBut = new javax.swing.JButton();
        fundhistoryPanel = new javax.swing.JPanel();
        fundhistoryScrollPanel = new javax.swing.JScrollPane();
        fundhistoryTable = new javax.swing.JTable();
        transPanel = new javax.swing.JPanel();
        transactionfilterLabel = new javax.swing.JLabel();
        transactionfilterComboBox = new javax.swing.JComboBox<>();
        transactionScrollPanel = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        newreqPanel = new javax.swing.JPanel();
        newreqLabel1 = new javax.swing.JLabel();
        reqField = new javax.swing.JTextField();
        newreqLabel2 = new javax.swing.JLabel();
        newreqScrollPanel = new javax.swing.JScrollPane();
        explainTextArea = new javax.swing.JTextArea();
        newreqsubmitBut = new javax.swing.JButton();
        reqhisPanel = new javax.swing.JPanel();
        reqhisfilterLabel = new javax.swing.JLabel();
        reqhisfilterComboBox = new javax.swing.JComboBox<>();
        reqhisScrollPanel = new javax.swing.JScrollPane();
        reqhisTable = new javax.swing.JTable();
        securityPanel = new javax.swing.JPanel();
        securityTab = new javax.swing.JTabbedPane();
        guestPanel = new javax.swing.JPanel();
        guestScrollPanel = new javax.swing.JScrollPane();
        guestTable = new javax.swing.JTable();
        guestHeaderLabel1 = new javax.swing.JLabel();
        guestnameLabel1 = new javax.swing.JLabel();
        guestnameField1 = new javax.swing.JTextField();
        guestcontactField = new javax.swing.JTextField();
        guestcontactLabel = new javax.swing.JLabel();
        guestflatField = new javax.swing.JTextField();
        guestflatLabel = new javax.swing.JLabel();
        guestnameField2 = new javax.swing.JTextField();
        guestnameLabel2 = new javax.swing.JLabel();
        guestheaderLabel2 = new javax.swing.JLabel();
        guestsubmitBut = new javax.swing.JButton();
        svPanel = new javax.swing.JPanel();
        svScrollPanel = new javax.swing.JScrollPane();
        svTable = new javax.swing.JTable();
        svheaderLabel = new javax.swing.JLabel();
        svnameLabel = new javax.swing.JLabel();
        svnameField = new javax.swing.JTextField();
        svcontactLabel = new javax.swing.JLabel();
        svcontactField = new javax.swing.JTextField();
        svsubmitBut = new javax.swing.JButton();
        signoutBut = new javax.swing.JButton();
        signinasLabel = new javax.swing.JLabel();
        signindesLabel = new javax.swing.JLabel();
        signinimageLabel = new javax.swing.JLabel();
        changepassLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        apartmentLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        acLabel1 = new javax.swing.JLabel();
        acLabel2 = new javax.swing.JLabel();
        nameshowLabel = new javax.swing.JLabel();
        contactshowLabel = new javax.swing.JLabel();
        apartmentshowLabel = new javax.swing.JLabel();
        emailshowLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundPanel.setBackground(new java.awt.Color(153, 153, 153));

        managerTab.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        javax.swing.GroupLayout acmanagePanelLayout = new javax.swing.GroupLayout(acmanagePanel);
        acmanagePanel.setLayout(acmanagePanelLayout);
        acmanagePanelLayout.setHorizontalGroup(
            acmanagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        acmanagePanelLayout.setVerticalGroup(
            acmanagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        managerTab.addTab("Account Management", acmanagePanel);

        javax.swing.GroupLayout rescomPanelLayout = new javax.swing.GroupLayout(rescomPanel);
        rescomPanel.setLayout(rescomPanelLayout);
        rescomPanelLayout.setHorizontalGroup(
            rescomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        rescomPanelLayout.setVerticalGroup(
            rescomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        managerTab.addTab("Resident Communication", rescomPanel);

        sopLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sopLabel1.setText("Name of Organization:");

        spoLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        spoLabel2.setText("Reason of Visit");

        spoLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        spoLabel3.setText("NID No. of One of the Officials:");

        spoLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        spoLabel4.setText("Full Name:");

        spoLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        spoLabel5.setText("Contact No.:");

        spoLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        spoLabel6.setText("Profession:");

        spoLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        spoLabel7.setText("Name of Work Institution");

        spoacBut.setText("OK");

        javax.swing.GroupLayout spoPanelLayout = new javax.swing.GroupLayout(spoPanel);
        spoPanel.setLayout(spoPanelLayout);
        spoPanelLayout.setHorizontalGroup(
            spoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spoPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(spoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sopLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(spoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spoLabel3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spoLabel2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(spoPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(spoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spoLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spoLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spoLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spoLabel7)
                    .addGroup(spoPanelLayout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(spoacBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        spoPanelLayout.setVerticalGroup(
            spoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spoPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(sopLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spoLabel2)
                .addGap(7, 7, 7)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spoLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spoLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spoLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spoLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spoLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spoacBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        spoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spotableScrollPanel.setViewportView(spoTable);

        spotableBut.setText("OK");
        spotableBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spotableButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout spotablePanelLayout = new javax.swing.GroupLayout(spotablePanel);
        spotablePanel.setLayout(spotablePanelLayout);
        spotablePanelLayout.setHorizontalGroup(
            spotablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spotablePanelLayout.createSequentialGroup()
                .addComponent(spotableScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(spotablePanelLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(spotableBut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        spotablePanelLayout.setVerticalGroup(
            spotablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spotablePanelLayout.createSequentialGroup()
                .addComponent(spotableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spotableBut)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        spoLayeredPanel.setLayer(spoPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        spoLayeredPanel.setLayer(spotablePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout spoLayeredPanelLayout = new javax.swing.GroupLayout(spoLayeredPanel);
        spoLayeredPanel.setLayout(spoLayeredPanelLayout);
        spoLayeredPanelLayout.setHorizontalGroup(
            spoLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spoLayeredPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spotablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(spoLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(spoLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(spoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        spoLayeredPanelLayout.setVerticalGroup(
            spoLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spoLayeredPanelLayout.createSequentialGroup()
                .addComponent(spotablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(spoLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spoLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        managerTab.addTab("Specialized Offiicial Entry", spoLayeredPanel);

        javax.swing.GroupLayout managerPanelLayout = new javax.swing.GroupLayout(managerPanel);
        managerPanel.setLayout(managerPanelLayout);
        managerPanelLayout.setHorizontalGroup(
            managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managerTab)
                .addContainerGap())
        );
        managerPanelLayout.setVerticalGroup(
            managerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        residentTab.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        addfundLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        addfundLabel1.setText("Type of Payment: (Name of MFS)");

        paymenttypecomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "bKash", "Rocket", "SureCash", "Nagad", " " }));
        paymenttypecomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymenttypecomboBoxActionPerformed(evt);
            }
        });

        addfundLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        addfundLabel2.setText("Amount Paid:");

        addfundLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        addfundLabel3.setText("Transaction ID:");

        addfundBut.setText("SUBMIT");
        addfundBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfundButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addfundPanelLayout = new javax.swing.GroupLayout(addfundPanel);
        addfundPanel.setLayout(addfundPanelLayout);
        addfundPanelLayout.setHorizontalGroup(
            addfundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addfundPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(addfundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountpaidField)
                    .addComponent(addfundLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addfundLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymenttypecomboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tidField)
                    .addComponent(addfundLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addfundPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addfundBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        addfundPanelLayout.setVerticalGroup(
            addfundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addfundPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(addfundLabel1)
                .addGap(18, 18, 18)
                .addComponent(paymenttypecomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addfundLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountpaidField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addfundLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tidField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(addfundBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        residentTab.addTab("Add Fund", addfundPanel);

        fundhistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fundhistoryScrollPanel.setViewportView(fundhistoryTable);

        javax.swing.GroupLayout fundhistoryPanelLayout = new javax.swing.GroupLayout(fundhistoryPanel);
        fundhistoryPanel.setLayout(fundhistoryPanelLayout);
        fundhistoryPanelLayout.setHorizontalGroup(
            fundhistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundhistoryScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        fundhistoryPanelLayout.setVerticalGroup(
            fundhistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundhistoryScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        residentTab.addTab("Funding History", fundhistoryPanel);

        transactionfilterLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        transactionfilterLabel.setText("Filter By:");

        transactionfilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Confirm/Report", "Reported", "Resolved" }));

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        transactionScrollPanel.setViewportView(transactionTable);

        javax.swing.GroupLayout transPanelLayout = new javax.swing.GroupLayout(transPanel);
        transPanel.setLayout(transPanelLayout);
        transPanelLayout.setHorizontalGroup(
            transPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transactionfilterLabel)
                .addGap(18, 18, 18)
                .addComponent(transactionfilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(transactionScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        transPanelLayout.setVerticalGroup(
            transPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transactionfilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionfilterLabel))
                .addGap(18, 18, 18)
                .addComponent(transactionScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );

        residentTab.addTab("Completed Transactions", transPanel);

        newreqLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        newreqLabel1.setText("Request: (Required)");

        newreqLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        newreqLabel2.setText("Explanation: (Optional)");

        explainTextArea.setColumns(20);
        explainTextArea.setRows(5);
        newreqScrollPanel.setViewportView(explainTextArea);

        newreqsubmitBut.setText("SUBMIT");
        newreqsubmitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newreqsubmitButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newreqPanelLayout = new javax.swing.GroupLayout(newreqPanel);
        newreqPanel.setLayout(newreqPanelLayout);
        newreqPanelLayout.setHorizontalGroup(
            newreqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newreqPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(newreqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newreqScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(newreqLabel2)
                    .addComponent(reqField)
                    .addComponent(newreqLabel1))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newreqPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newreqsubmitBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        newreqPanelLayout.setVerticalGroup(
            newreqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newreqPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(newreqLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reqField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newreqLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newreqScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(newreqsubmitBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        residentTab.addTab("New Request", newreqPanel);

        reqhisfilterLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        reqhisfilterLabel.setText("Filter By:");

        reqhisfilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Confirm/Report", "Reported", "Resolved" }));

        reqhisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reqhisScrollPanel.setViewportView(reqhisTable);

        javax.swing.GroupLayout reqhisPanelLayout = new javax.swing.GroupLayout(reqhisPanel);
        reqhisPanel.setLayout(reqhisPanelLayout);
        reqhisPanelLayout.setHorizontalGroup(
            reqhisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reqhisPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reqhisfilterLabel)
                .addGap(18, 18, 18)
                .addComponent(reqhisfilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(reqhisScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        reqhisPanelLayout.setVerticalGroup(
            reqhisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reqhisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reqhisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reqhisfilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reqhisfilterLabel))
                .addGap(18, 18, 18)
                .addComponent(reqhisScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );

        residentTab.addTab("Request History", reqhisPanel);

        javax.swing.GroupLayout residentPanelLayout = new javax.swing.GroupLayout(residentPanel);
        residentPanel.setLayout(residentPanelLayout);
        residentPanelLayout.setHorizontalGroup(
            residentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(residentTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        residentPanelLayout.setVerticalGroup(
            residentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(residentTab)
        );

        securityTab.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        guestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        guestScrollPanel.setViewportView(guestTable);

        guestHeaderLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        guestHeaderLabel1.setText("Info of Guest");

        guestnameLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        guestnameLabel1.setText("Full Name:");

        guestnameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestnameField1ActionPerformed(evt);
            }
        });

        guestcontactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestcontactFieldActionPerformed(evt);
            }
        });

        guestcontactLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        guestcontactLabel.setText("Contact No.:");

        guestflatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestflatFieldActionPerformed(evt);
            }
        });

        guestflatLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        guestflatLabel.setText("Flat No.:");

        guestnameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestnameField2ActionPerformed(evt);
            }
        });

        guestnameLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        guestnameLabel2.setText("Name:");

        guestheaderLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        guestheaderLabel2.setText("Whom to Visit");

        guestsubmitBut.setText("SUBMIT");
        guestsubmitBut.setMaximumSize(new java.awt.Dimension(75, 30));
        guestsubmitBut.setMinimumSize(new java.awt.Dimension(75, 30));
        guestsubmitBut.setPreferredSize(new java.awt.Dimension(75, 30));
        guestsubmitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestsubmitButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout guestPanelLayout = new javax.swing.GroupLayout(guestPanel);
        guestPanel.setLayout(guestPanelLayout);
        guestPanelLayout.setHorizontalGroup(
            guestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestPanelLayout.createSequentialGroup()
                .addGroup(guestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guestPanelLayout.createSequentialGroup()
                        .addContainerGap(154, Short.MAX_VALUE)
                        .addGroup(guestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestPanelLayout.createSequentialGroup()
                                .addComponent(guestHeaderLabel1)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guestPanelLayout.createSequentialGroup()
                                .addGroup(guestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guestnameLabel1)
                                    .addComponent(guestnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guestcontactLabel)
                                    .addComponent(guestcontactField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guestnameLabel2)
                                    .addComponent(guestnameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guestflatLabel)
                                    .addComponent(guestflatField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78))))
                    .addGroup(guestPanelLayout.createSequentialGroup()
                        .addGroup(guestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guestPanelLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(guestheaderLabel2))
                            .addGroup(guestPanelLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(guestsubmitBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(guestScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        guestPanelLayout.setVerticalGroup(
            guestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guestScrollPanel)
            .addGroup(guestPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(guestHeaderLabel1)
                .addGap(29, 29, 29)
                .addComponent(guestnameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestnameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guestcontactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestcontactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(guestheaderLabel2)
                .addGap(29, 29, 29)
                .addComponent(guestnameLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestnameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guestflatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestflatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guestsubmitBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        securityTab.addTab("Guest", guestPanel);

        svTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        svScrollPanel.setViewportView(svTable);

        svheaderLabel.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        svheaderLabel.setText("Information of Guest");

        svnameLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        svnameLabel.setText("Full Name");

        svnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svnameFieldActionPerformed(evt);
            }
        });

        svcontactLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        svcontactLabel.setText("Contact No.");

        svcontactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svcontactFieldActionPerformed(evt);
            }
        });

        svsubmitBut.setText("SUBMIT");
        svsubmitBut.setPreferredSize(new java.awt.Dimension(75, 30));
        svsubmitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svsubmitButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout svPanelLayout = new javax.swing.GroupLayout(svPanel);
        svPanel.setLayout(svPanelLayout);
        svPanelLayout.setHorizontalGroup(
            svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svPanelLayout.createSequentialGroup()
                .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(svPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(svheaderLabel))
                    .addGroup(svPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(svcontactLabel)
                                .addComponent(svnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(svnameLabel))
                            .addComponent(svcontactField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(svPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(svsubmitBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(svScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        svPanelLayout.setVerticalGroup(
            svPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(svScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
            .addGroup(svPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(svheaderLabel)
                .addGap(101, 101, 101)
                .addComponent(svnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(svnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(svcontactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(svcontactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(svsubmitBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        securityTab.addTab("Scheduled Visitor", svPanel);

        javax.swing.GroupLayout securityPanelLayout = new javax.swing.GroupLayout(securityPanel);
        securityPanel.setLayout(securityPanelLayout);
        securityPanelLayout.setHorizontalGroup(
            securityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(securityTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        securityPanelLayout.setVerticalGroup(
            securityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(securityTab)
        );

        panelLayers.setLayer(managerPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelLayers.setLayer(residentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelLayers.setLayer(securityPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayersLayout = new javax.swing.GroupLayout(panelLayers);
        panelLayers.setLayout(panelLayersLayout);
        panelLayersLayout.setHorizontalGroup(
            panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayersLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(residentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayersLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(securityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelLayersLayout.setVerticalGroup(
            panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(residentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(securityPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        signoutBut.setText("Sign Out");
        signoutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButActionPerformed(evt);
            }
        });

        signinasLabel.setText("Signed In As:");

        changepassLabel.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        changepassLabel.setText("Change Password");

        nameLabel.setText("Full Name:");

        contactLabel.setText("Contact No.:");

        apartmentLabel.setText("Apartment No.:");

        emailLabel.setText("E-mail Address:");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(acLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(acLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(signoutBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameLabel)
                                    .addComponent(contactLabel)
                                    .addComponent(apartmentLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(nameshowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(contactshowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(apartmentshowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailshowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(signinasLabel)
                                .addGap(18, 18, 18)
                                .addComponent(signindesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(signinimageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changepassLabel)
                        .addGap(18, 18, 18)))
                .addComponent(panelLayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signinasLabel)
                    .addComponent(signindesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signinimageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changepassLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameshowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactshowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apartmentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apartmentshowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailshowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(acLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(acLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signoutBut, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(panelLayers)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signoutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButActionPerformed
        // TODO add your handling code here:
        LoginPage tmp = new LoginPage();
        tmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signoutButActionPerformed

    private void svcontactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svcontactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svcontactFieldActionPerformed

    private void svnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svnameFieldActionPerformed

    private void svsubmitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svsubmitButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svsubmitButActionPerformed

    private void guestnameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestnameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestnameField1ActionPerformed

    private void guestcontactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestcontactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestcontactFieldActionPerformed

    private void guestflatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestflatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestflatFieldActionPerformed

    private void guestnameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestnameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestnameField2ActionPerformed

    private void guestsubmitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestsubmitButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guestsubmitButActionPerformed

    private void paymenttypecomboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymenttypecomboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymenttypecomboBoxActionPerformed

    private void addfundButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfundButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addfundButActionPerformed

    private void newreqsubmitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newreqsubmitButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newreqsubmitButActionPerformed

    private void spotableButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spotableButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spotableButActionPerformed

    /*
     * User define functions 
     */
    
    private void initializeSelf(){
        
        signinimageLabel.setIcon(Resizing.resizeIcon("images/bla.jpg", signinimageLabel));

        choosePanel(LoginPage.getChoice());
    }
    
    private void choosePanel(String choice) {
        managerPanel.setVisible(false);
        residentPanel.setVisible(false);
        securityPanel.setVisible(false);

        switch (choice) {
            case "manager":
                managerPanel.setVisible(true);
                break;
            case "resident":
                residentPanel.setVisible(true);
                break;
            case "security":
                securityPanel.setVisible(true);
                break;
            default:
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommonInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommonInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommonInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommonInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommonInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acLabel1;
    private javax.swing.JLabel acLabel2;
    private javax.swing.JPanel acmanagePanel;
    private javax.swing.JButton addfundBut;
    private javax.swing.JLabel addfundLabel1;
    private javax.swing.JLabel addfundLabel2;
    private javax.swing.JLabel addfundLabel3;
    private javax.swing.JPanel addfundPanel;
    private javax.swing.JTextField amountpaidField;
    private javax.swing.JLabel apartmentLabel;
    private javax.swing.JLabel apartmentshowLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel changepassLabel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel contactshowLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailshowLabel;
    private javax.swing.JTextArea explainTextArea;
    private javax.swing.JPanel fundhistoryPanel;
    private javax.swing.JScrollPane fundhistoryScrollPanel;
    private javax.swing.JTable fundhistoryTable;
    private javax.swing.JLabel guestHeaderLabel1;
    private javax.swing.JPanel guestPanel;
    private javax.swing.JScrollPane guestScrollPanel;
    private javax.swing.JTable guestTable;
    private javax.swing.JTextField guestcontactField;
    private javax.swing.JLabel guestcontactLabel;
    private javax.swing.JTextField guestflatField;
    private javax.swing.JLabel guestflatLabel;
    private javax.swing.JLabel guestheaderLabel2;
    private javax.swing.JTextField guestnameField1;
    private javax.swing.JTextField guestnameField2;
    private javax.swing.JLabel guestnameLabel1;
    private javax.swing.JLabel guestnameLabel2;
    private javax.swing.JButton guestsubmitBut;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel managerPanel;
    private javax.swing.JTabbedPane managerTab;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameshowLabel;
    private javax.swing.JLabel newreqLabel1;
    private javax.swing.JLabel newreqLabel2;
    private javax.swing.JPanel newreqPanel;
    private javax.swing.JScrollPane newreqScrollPanel;
    private javax.swing.JButton newreqsubmitBut;
    private javax.swing.JLayeredPane panelLayers;
    private javax.swing.JComboBox<String> paymenttypecomboBox;
    private javax.swing.JTextField reqField;
    private javax.swing.JPanel reqhisPanel;
    private javax.swing.JScrollPane reqhisScrollPanel;
    private javax.swing.JTable reqhisTable;
    private javax.swing.JComboBox<String> reqhisfilterComboBox;
    private javax.swing.JLabel reqhisfilterLabel;
    private javax.swing.JPanel rescomPanel;
    private javax.swing.JPanel residentPanel;
    private javax.swing.JTabbedPane residentTab;
    private javax.swing.JPanel securityPanel;
    private javax.swing.JTabbedPane securityTab;
    private javax.swing.JLabel signinasLabel;
    private javax.swing.JLabel signindesLabel;
    private javax.swing.JLabel signinimageLabel;
    private javax.swing.JButton signoutBut;
    private javax.swing.JLabel sopLabel1;
    private javax.swing.JLabel spoLabel2;
    private javax.swing.JLabel spoLabel3;
    private javax.swing.JLabel spoLabel4;
    private javax.swing.JLabel spoLabel5;
    private javax.swing.JLabel spoLabel6;
    private javax.swing.JLabel spoLabel7;
    private javax.swing.JLayeredPane spoLayeredPanel;
    private javax.swing.JPanel spoPanel;
    private javax.swing.JTable spoTable;
    private javax.swing.JButton spoacBut;
    private javax.swing.JButton spotableBut;
    private javax.swing.JPanel spotablePanel;
    private javax.swing.JScrollPane spotableScrollPanel;
    private javax.swing.JPanel svPanel;
    private javax.swing.JScrollPane svScrollPanel;
    private javax.swing.JTable svTable;
    private javax.swing.JTextField svcontactField;
    private javax.swing.JLabel svcontactLabel;
    private javax.swing.JLabel svheaderLabel;
    private javax.swing.JTextField svnameField;
    private javax.swing.JLabel svnameLabel;
    private javax.swing.JButton svsubmitBut;
    private javax.swing.JTextField tidField;
    private javax.swing.JPanel transPanel;
    private javax.swing.JScrollPane transactionScrollPanel;
    private javax.swing.JTable transactionTable;
    private javax.swing.JComboBox<String> transactionfilterComboBox;
    private javax.swing.JLabel transactionfilterLabel;
    // End of variables declaration//GEN-END:variables
}
