/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaces;

import javax.swing.JOptionPane;


/**
 *
 * @author Dragneel
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    static String choose;

    public LoginPage() {
        initComponents();
        
        initializeSelf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DescriptionPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        ContactNoField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        contactLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        forgotLabel = new javax.swing.JLabel();
        managerBut = new javax.swing.JButton();
        residentBut = new javax.swing.JButton();
        secureBut = new javax.swing.JButton();
        closeApplication = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        desLabel1 = new javax.swing.JLabel();
        desLabel2 = new javax.swing.JLabel();
        desLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        desLabel4 = new javax.swing.JLabel();
        desLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        DescriptionPanel.setBackground(new java.awt.Color(153, 153, 153));
        DescriptionPanel.setBorder(null);

        LoginPanel.setBackground(new java.awt.Color(0, 153, 204));

        contactLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        contactLabel.setText("Contact No.");

        passLabel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        passLabel.setText("Password");

        forgotLabel.setFont(new java.awt.Font("sansserif", 1, 8)); // NOI18N
        forgotLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        forgotLabel.setText("Forgot Password?");
        forgotLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotLabelMouseClicked(evt);
            }
        });
        forgotLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                forgotLabelKeyTyped(evt);
            }
        });

        managerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButActionPerformed(evt);
            }
        });

        residentBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentButActionPerformed(evt);
            }
        });

        secureBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secureButActionPerformed(evt);
            }
        });

        closeApplication.setText("Close Appplication");
        closeApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeApplicationActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Log In");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forgotLabel)
                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passLabel)
                        .addComponent(ContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addComponent(managerBut, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(residentBut, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(secureBut, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(closeApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(contactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(forgotLabel)
                .addGap(75, 75, 75)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(residentBut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secureBut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managerBut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(closeApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        desLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        desLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desLabel1.setText("Welcome");

        desLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        desLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desLabel2.setText("to");

        desLabel3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        desLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desLabel3.setText("Apartment Information");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setText("System");

        desLabel4.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        desLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desLabel4.setText("Nikunja Residence");

        desLabel5.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        desLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desLabel5.setText("142 Hate Road, Tejgaon");

        javax.swing.GroupLayout DescriptionPanelLayout = new javax.swing.GroupLayout(DescriptionPanel);
        DescriptionPanel.setLayout(DescriptionPanelLayout);
        DescriptionPanelLayout.setHorizontalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DescriptionPanelLayout.createSequentialGroup()
                .addGroup(DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DescriptionPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(desLabel3))
                    .addGroup(DescriptionPanelLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(desLabel2))
                    .addGroup(DescriptionPanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(desLabel1))
                    .addGroup(DescriptionPanelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(DescriptionPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desLabel4)
                            .addGroup(DescriptionPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(desLabel5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DescriptionPanelLayout.setVerticalGroup(
            DescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(desLabel1)
                .addGap(18, 18, 18)
                .addComponent(desLabel2)
                .addGap(18, 18, 18)
                .addComponent(desLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(141, 141, 141)
                .addComponent(desLabel4)
                .addGap(18, 18, 18)
                .addComponent(desLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(LoginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void secureButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureButActionPerformed
        // TODO add your handling code here:
        choose = "security";
        goNextPage();
    }//GEN-LAST:event_secureButActionPerformed

    private void closeApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeApplicationActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeApplicationActionPerformed

    private void managerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButActionPerformed
        // TODO add your handling code here:
        choose = "manager";
        goNextPage();
    }//GEN-LAST:event_managerButActionPerformed

    private void residentButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentButActionPerformed
        // TODO add your handling code here:
        choose = "resident";
        goNextPage();
    }//GEN-LAST:event_residentButActionPerformed

    private void forgotLabelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_forgotLabelKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_forgotLabelKeyTyped

    private void forgotLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showInputDialog("Provide valid e-mail address: ");
        JOptionPane.showMessageDialog(null, "Your password has been sent to your e-mail");
    }//GEN-LAST:event_forgotLabelMouseClicked

    /*
     * User define functions 
     */
    private void initializeSelf() {

        managerBut.setIcon(Resizing.resizeIcon("images/ara.jpg", managerBut));
        residentBut.setIcon(Resizing.resizeIcon("images/sata.jpg", residentBut));
        secureBut.setIcon(Resizing.resizeIcon("images/shama.jpg", secureBut));
    }



    public void goNextPage() {
        CommonInterface tmp = new CommonInterface();
        tmp.setVisible(true);
        this.dispose();
    }

    public static String getChoice() {
        return choose;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactNoField;
    private javax.swing.JPanel DescriptionPanel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton closeApplication;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel desLabel1;
    private javax.swing.JLabel desLabel2;
    private javax.swing.JLabel desLabel3;
    private javax.swing.JLabel desLabel4;
    private javax.swing.JLabel desLabel5;
    private javax.swing.JLabel forgotLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton managerBut;
    private javax.swing.JLabel passLabel;
    private javax.swing.JButton residentBut;
    private javax.swing.JButton secureBut;
    // End of variables declaration//GEN-END:variables
}
